language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
#  - osx  # Unfortunately Py2.7 seems broken on travis as of 2017-07
install:
  - python setup.py install
script:
  - python setup.py test
notifications:
  email:
    on_success: change
    on_failure: always
